### PR TITLE
Removed useless folder of images from statement

### PR DESCRIPTION
**Pull request by dominguezcelada**

### CODE REVIEW

**Comment by stefanosaittamrf** [comment]
You should edit the `README.md` in order to add the images there

**Comment by dominguezcelada** [comment]
Good catch!

**Comment by stefanosaittamrf** [comment]
Actually the images are still pointing to the old repo 🙄

**Comment by dominguezcelada** [comment]
Added

**Comment by dominguezcelada** [comment]
Closing PR until we have permissions to merge.

**Comment by dominguezcelada** [comment]
Reopened Pull Request

**Pull request merged**
